{
 "title": "Stock - NSE",
 "time": { "from": "now-1y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "stock",
    "label": "Stock Ticker",
    "query": "select distinct(ticker) from stock_tickers"
   }
  ]
 },
 "panels": [
  { "title": "Stock Identifiers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Stock Differentials",
   "type": "table",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT ticker, first(low, time), last(low, time), last(low, time) - first(low, time) as differential, (last(low, time) - first(low, time))*100/first(low, time) as pct\n  FROM stock_prices WHERE $__timeFilter(time)\n  GROUP BY ticker;\n\n-- SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY ticker) FROM stock_prices;"
    }
   ]
  },
  {
   "title": "High Volumes",
   "type": "table",
   "gridPos": { "h": 10, "w": 4, "x": 7, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT ticker, sum(volume)\n  FROM stock_prices WHERE $__timeFilter(time)\n  GROUP BY ticker ORDER BY 2 desc;\n\n-- SELECT percentile_cont(0.5) WITHIN GROUP (ORDER BY ticker) FROM stock_prices;"
    }
   ]
  },
  {
   "title": "Stock Tickers",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  *\nFROM stock_tickers\nORDER BY 1"
    }
   ]
  },
  { "title": "Stock Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Value Change",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  last(close, time) - first(open, time) as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pct Change",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (last(close, time) - first(open, time))*100/first(open, time) as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Value Change",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (last(volume, time) - first(volume, time)) as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Pct Change",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (last(volume, time) - first(volume, time))*100/first(volume, time) as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stock Prices - $stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  low,\n  high,\n  open,\n  close\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Stock Prices - Volume - $stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  volume\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max 1 Day Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (close - open)*100/open as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Std Dev 1 Day Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (close - open)*100/open as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mean 1 Day Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  (close - open)*100/open as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max WoW Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('7 days', time) AS week,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY week\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Std Dev WoW Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('7 days', time) AS week,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY week\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mean WoW Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('7 days', time) AS week,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY week\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Intra day Diff Pct - $stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  (close - open)*100/open as diff\nFROM stock_prices\nWHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "WoW Mvg Diff Pct - $stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('7 days', time) AS week,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct\n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY week\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '7d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max MoM Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('1 month', time) AS month,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY month\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Std Dev MoM Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('1 month', time) AS month,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY month\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mean MoM Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('1 month', time) AS month,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY month\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max QoQ Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "StdDev QoQ Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mean QoQ Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "MoM Diff Pct - $stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('1 month', time) AS month,\n--   (last(close, time) - first(close, time))*100/first(close, time) as month_diff_pct\n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY month\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '30d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "QoQ Diff Pct - $stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as quarter_diff_pct\n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '90d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Max YoY Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "StdDev YoY Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "stdDev" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Mean YoY Variation",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 51 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as week_diff_pct \n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  },
  {
   "title": "YoY Diff Pct - $stock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "rawSql": "-- SELECT time_bucket('3 months', time) AS quarter,\n--   (last(close, time) - first(close, time))*100/first(close, time) as quarter_diff_pct\n-- FROM stock_prices\n-- WHERE\n--   $__timeFilter(time) and ticker = '$stock' GROUP BY quarter\n-- ORDER BY 1\n\nselect time, (last(close, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) - first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING)) * 100/ first(open, time) OVER (ORDER BY time RANGE BETWEEN '365d' PRECEDING AND '0d' FOLLOWING) from stock_prices WHERE\n  $__timeFilter(time) and ticker = '$stock'\nORDER BY 1"
    }
   ]
  }
 ]
}